### ISSUE TITLE
nonfree indirect dependency: jsmin

### ISSUE THREAD

**Issue by JacobKfromIRC** [divVerent/aaaaxy#389]
Hello, I wanted to add AAAAXY to the Free Software Directory and LibreGameWiki, so I ran `go mod vendor` then used scancode-toolkit to look for nonfree licenses.  Unfortunately it looks like there is one nonfree second-level dependency. AAAAXY depends on [zenity](https://github.com/ncruces/zenity) which depends on [jsmin](https://github.com/dchest/jsmin), which is based on Douglas Crockford's JSMin which has a license that includes "The Software shall be used for Good, not Evil.".

My understanding is that this would be a problem for F-Droid, but I'm not sure.

The nonfree code is a JavaScript minifier, so maybe removing or replacing the dependency wouldn't be that difficult, but that would require modifying zenity. I'm not sure what the best path forward is. The zenity package may not see this as an issue.

**Comment by pombredanne** [comment]
@JacobKfromIRC FWIW, I ran my (new) go-inspector scancode-toolkit plugin on the built binary and there is sign of the jsmin module being used anywhere. Based on https://github.com/ncruces/zenity/blob/848f6d01d3fb9b45d61836d73d1f60d783db235b/internal/zenutil/osa_generator.go#L16 this seems to only be used as a tool by zenity and never exported nor used here?

This is can be a common case with indirect dependencies: they may show up in go.mod and go.sum  but end up not being used in the built binary.

**Comment by JacobKfromIRC** [comment]
Thank you. Hopefully that means it's actually not an issue for F-Droid, in which case maybe the issue should be closed.

I feel a bit foolish now for opening the issue without looking into it more than I did 😅️ Though, I guess even if it's not a problem for F-Droid inclusion I don't know whether it's an issue for this project anyway.

**Comment by pombredanne** [comment]
> I feel a bit foolish now for opening the issue without looking into it more than I did

Don't! There is nothing obvious there: the go.mod reports this as an indirect requirement but this is not used. You need to analyze the binary to find the truth about this.

**Comment by seabass-labrax** [comment]
It seems to me that jsmin is used exclusively for the macOS target of the zenity Go package:

<https://github.com/ncruces/zenity/blob/848f6d01d3fb9b45d61836d73d1f60d783db235b/internal/zenutil/osa_generator.go#L91>

With this in mind, it would not be considered a problem for F-Droid, as F-Droid is designed to run on Android devices rather than macOS.

I can't speak for the Free Software Directory, but my personal feeling is that it's mostly academic whether or not a package for a proprietary platform is 100% free. After all, you typically need Windows header files to link an application for Windows, and that doesn't stop, say, Blender or GIMP from being considered free. The version which runs on GNU/Linux is free, and that would be enough for me :)
